prefix = "."
stop-words = "stopwords.txt"

dataset = "output"
corpus = "line_IR.toml"
index = "idx_IR"

query-judgements = "qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "queries.txt"
query-id-start = 1